-- AlterTable
ALTER TABLE "characters" ADD COLUMN "sta" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "characters" ADD COLUMN "wis" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "characters" ADD COLUMN "spl" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "characters" ADD COLUMN "crt" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "characters" ADD COLUMN "availableTraitPoints" INTEGER NOT NULL DEFAULT 0;
